openapi: 3.0.3
info:
  title: Suite Sync User Management API
  description: API for managing users in the hotel management system (Customers, Staff, and Admins)
  version: 1.0.0
  contact:
    name: Suite Sync Team
    email: support@suitesync.com

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Users
    description: User management operations

paths:
  /api/v1/users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Retrieve a list of all users in the system
      operationId: getAllUsers
      security:
        - bearerAuth: []
      parameters:
        - name: userType
          in: query
          description: Filter users by type
          required: false
          schema:
            $ref: '#/components/schemas/UserType'
        - name: page
          in: query
          description: Page number (0-based)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPageResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Users
      summary: Create a new user
      description: Create a new user in the system
      operationId: createUser
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/users/{userId}:
    get:
      tags:
        - Users
      summary: Get user by ID
      description: Retrieve a specific user by their ID
      operationId: getUserById
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Users
      summary: Update user
      description: Update an existing user's information
      operationId: updateUser
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: ID of the user to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Users
      summary: Delete user
      description: Delete a user from the system
      operationId: deleteUser
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: ID of the user to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/users/{userId}/activate:
    post:
      tags:
        - Users
      summary: Activate user account
      description: Activate a user account using the confirmation token sent via email
      operationId: activateUser
      security: []
      parameters:
        - name: userId
          in: path
          description: ID of the user to activate
          required: true
          schema:
            type: integer
            format: int64
        - name: token
          in: query
          description: Confirmation token sent to user's email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User activated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UserType:
      type: string
      enum:
        - CUSTOMER
        - STAFF
        - ADMIN
      description: Type of user in the system

    UserStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - SUSPENDED
      description: Status of the user account

    CreateUserRequest:
      type: object
      required:
        - email
        - firstName
        - lastName
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: john.doe@example.com
        firstName:
          type: string
          minLength: 1
          maxLength: 100
          description: User's first name
          example: John
        lastName:
          type: string
          minLength: 1
          maxLength: 100
          description: User's last name
          example: Doe
        phoneNumber:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
          description: User's phone number in E.164 format
          example: +1234567890
        userType:
          $ref: '#/components/schemas/UserType'
        password:
          type: string
          minLength: 8
          maxLength: 100
          description: User's password (must be at least 8 characters)
          format: password
          example: SecurePassword123!
        address:
          $ref: '#/components/schemas/Address'

    UpdateUserRequest:
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 100
          description: User's first name
          example: John
        lastName:
          type: string
          minLength: 1
          maxLength: 100
          description: User's last name
          example: Doe
        phoneNumber:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
          description: User's phone number in E.164 format
          example: +1234567890
        userType:
          $ref: '#/components/schemas/UserType'
        address:
          $ref: '#/components/schemas/Address'

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the user
          example: 1
        email:
          type: string
          format: email
          description: User's email address
          example: john.doe@example.com
        firstName:
          type: string
          description: User's first name
          example: John
        lastName:
          type: string
          description: User's last name
          example: Doe
        phoneNumber:
          type: string
          description: User's phone number
          example: +1234567890
        userType:
          $ref: '#/components/schemas/UserType'
        status:
          $ref: '#/components/schemas/UserStatus'
        address:
          $ref: '#/components/schemas/Address'
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the user was created
          example: 2023-01-15T10:30:00Z
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the user was last updated
          example: 2023-01-15T10:30:00Z

    Address:
      type: object
      properties:
        street:
          type: string
          description: Street address
          example: 123 Main Street
        city:
          type: string
          description: City
          example: New York
        state:
          type: string
          description: State or province
          example: NY
        postalCode:
          type: string
          description: Postal or ZIP code
          example: 10001
        country:
          type: string
          description: Country
          example: USA

    UserPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        page:
          type: integer
          description: Current page number
          example: 0
        size:
          type: integer
          description: Number of items per page
          example: 20
        totalElements:
          type: integer
          format: int64
          description: Total number of users
          example: 100
        totalPages:
          type: integer
          description: Total number of pages
          example: 5

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the error
          example: 2023-01-15T10:30:00Z
        status:
          type: integer
          description: HTTP status code
          example: 400
        error:
          type: string
          description: Error type
          example: Bad Request
        message:
          type: string
          description: Error message
          example: Invalid input data
        path:
          type: string
          description: Request path
          example: /api/v1/users

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


